### ISSUE TITLE
Missing doccumentation

### ISSUE THREAD

**Issue by foxycode** [Arachne/SecurityVerification#2]
I'd like to use this with `Arachne/Verifier`, but docs doesn't explain how to use it. I tried to add extension:
```yaml
extensions:
    arachne.security: Arachne\Security\DI\SecurityExtension
    arachne.verifier: Arachne\Verifier\DI\VerifierExtension
    arachne.securityVerification: Arachne\SecurityVerification\DI\SecurityVerificationExtension
    annotations: Kdyby\Annotations\DI\AnnotationsExtension
```

But it displayes error:
```
Non-static method App\Libs\Security\AuthorizatorFactory::create() should not be called statically
```

`AuthorizatorFactory.php`
```php
<?php

declare(strict_types=1);

namespace App\Libs\Security;

use Arachne\Security\Authorization\AuthorizatorInterface;
use Arachne\Security\Authorization\Permission;
use Arachne\Security\Authorization\PermissionAuthorizator;

final class AuthorizatorFactory
{
    /**
     * @var AdminFirewall
     */
    private $firewall;

    public function __construct(AdminFirewall $adminFirewall)
    {
        $this->firewall = $adminFirewall;
    }

    public function create(): AuthorizatorInterface
    {
        $permission = new Permission;

        $permission->addRole('admin');

        $permission->addResource('datacenter');
        $permission->addResource('ipAddress');
        $permission->addResource('ipRange');
        $permission->addResource('macAddress');

        $permission->allow('admin', ['datacenter', 'ipAddress', 'ipRange', 'macAddress'], 'view');

        return new PermissionAuthorizator($this->firewall, $permission);
    }
}
```

**Comment by enumag** [comment]
Looks like my configuration from the article is still wrong. Really sorry about that. Personally I'm doing everything in DI extensions so my neon is a bit rusty.

It should work with something like this. Please let me know about the result.

```
services:
    admin.authorizator.factory: App\Module\AdminModule\Security\AuthorizatorFactory
    admin.authorizator:
        factory: @admin.authorizator.factory::create
        tag:
            arachne.security.authorizator: admin
```
